Fix broken CI due to rake-compiler error on Ruby < 2.6
The recently released rake-compiler 1.2.4 breaks compatibility with Ruby
2.5 and below. It is causing concurrent-ruby CI jobs to fail with errors
like this:

```
NoMethodError: undefined method `cleanpath' for "tmp/x86_64-linux/concurrent_ruby_ext/2.3.8":String
```

The rake-compiler regression has been reported here:

https://github.com/rake-compiler/rake-compiler/issues/224

As a workaround, this PR updates the ruby-concurrent Gemfile to avoid
rake-compiler 1.2.4. This should fix the broken CI jobs.